### ISSUE TITLE
No plugin settings

### ISSUE THREAD

**Issue by huachuman** [CtrlAltFocus/obsidian-plugin-auto-tag#7]
I wish I could add my API key but there's no plugin settings for this. 

![image](https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag/assets/125603964/8bcca880-1a55-4387-b9c9-ab1f2172cd45)

![image](https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag/assets/125603964/4e187c03-9c4a-4bf4-b9da-c6cbb7ebb647)

**Comment by CtrlAltFocus** [comment]
Thank you for letting me know!
I will look into this right away.

Extra info: 
- windows, mac, or mobile app?

This is what you should see, normally (and this is what I am seeing):
<img width="1086" alt="image" src="https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag/assets/128191353/fff71f2a-4e38-4e49-bc26-d7e1de7e46b6">

**Comment by CtrlAltFocus** [comment]
Early tests:
- mac : no issue on my end
- windows 11 : no issue either
- android app : cannot enable the plugin (same with many plugins btw 🤔), will try to debug that
- iOS app : need to find a device to test again
- linux : have no linux distro to test with, will ask around

**Comment by CtrlAltFocus** [comment]
I learned that there is a "debug info" command in Obsidian :-) 
It displays something like this:
<img width="564" alt="image" src="https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag/assets/128191353/f1e88121-a065-4e0f-b501-6d5d257a0b4e">

That could be helpful :-) although it provides too much info. Just the first 4 lines (if possible).

**Comment by CtrlAltFocus** [comment]
@huachuman  
Could you try updating / installing version 0.2.8 ?

I improved the code but also disabled the writing to log file by default.
Although **I was not able to reproduce the error**, I had a look at the code and improved a part related to writing to a log file, which miiiight perhaps cause issues (file access on various platforms is prone to exceptions).

**Comment by huachuman** [comment]
I'm on Windows 11. I just updated the plugin and although it didn't seem to work at first, restarting obsidian after updating the plugin worked!!

**Comment by CtrlAltFocus** [comment]
Awesome, glad it works now.
As it worked for me on Win11... it's possible or likely that you didn't
have a recent enough version? 🤔

Which means I need to try and test with older versions to be able to
indicate the minimum supported version more accurately 🤞👍

**Comment by huachuman** [comment]
Insider build.

However I have never ever seen this problem and have installed hundreds of community plugins before.

**Comment by CtrlAltFocus** [comment]
So my fix did fix something, glad 😄  and sorry for that!
